Changes in documentation
nbcl/primality pull request #11
Opened 2020-10-05 06:51 UTC by AkshayaKulasekaran

In reference to issue #8 
Unfortunately, I wasn't able to summarize the mentioned theories to my satisfaction, will try to do so at a later date

2020-10-06 05:00 UTC, nbcl commented
**🎉 Thanks for your interest in contributing to Primality**

Hello @AkshayaKulasekaran! 

I just reviewed the request, it looks good!

There seem to be a minor issue in the provided links, as they do not correspond to the correct source.

For example, the third quote references the OEIS Foundation but the url redirects to Wikipedia.

I suggest the provided link to each of the citations comes from each of the following websites respectively:

1. For the first source: https://dl.acm.org/
2. For the second source: https://www.ams.org/
3. For the third source: https://oeis.org/
 
If you have trouble finding the correct sources, you can let me know by removing the hyperlinks and adding this change to your fork. If that is the case, I will move foward with the request and the correct sources shall be added on a later date.

**Thank you!**

2020-10-06 05:02 UTC, nbcl reviewed
Change citation hyperlinks to represent correct source

2020-10-07 03:48 UTC, thisisjaymehta commented on theory/THEORY.md
> +1. Zhang, Z and Tang, M. (2003), ["Finding strong pseudoprimes to several bases. II"](http://www.jointmathematicsmeetings.org/mcom/2003-72-244/S0025-5718-03-01545-X/S0025-5718-03-01545-X.pdf), Mathem
Should this bullet say 2

2020-10-07 03:50 UTC, thisisjaymehta requested changes
Bullets should say 1,2 and 3 instead of 1,1 and 1 in Theory Subsection

2020-10-08 19:26 UTC, AkshayaKulasekaran commented
Heya @nbcl!
So sorry for the delay, I've redone the links in THEORY.md
Also, @thisisjaymehta, that's actually the mark-up for ordered lists, so yeah... 😅

2020-10-08 19:28 UTC, AkshayaKulasekaran commented
> Bullets should say 1,2 and 3 instead of 1,1 and 1 in Theory Subsection
Check out the rich text, it should be a bit clearer

2020-10-08 19:33 UTC, AkshayaKulasekaran commented
Ah, one more thing... the modified links redirect to the general website, while the previous ones redirect to the specific papers/ info about those papers. Just pointing that out, in case that wasn't what you wanted.

2020-10-09 04:51 UTC, thisisjaymehta approved these changes

2020-10-17 16:17 UTC, nbcl commented
Hello @AkshayaKulasekaran! 

I think there was a small misunderstandment, my apologies.

When I suggested, for example, `https://www.ams.org/` as a source, I didn't mean that exact site, I meant the source document hosted on that specific site. 

A correct citation should look similar to`https://www.ams.org/documents/source.pdf`, where `source.pdf` represents the document you are trying to cite.

Again, if you encounter problems finding the specific sources, I would suggest to remove the hyperlinks so we can move forward with the request! This being the case, the exact sources shall be added on a later date.

**Thank you!**

2020-10-17 16:18 UTC, nbcl reviewed
Change or remove citation hyperlinks to represent exact source

2020-11-07 08:13 UTC, AkshayaKulasekaran commented
@nbcl, I was able to find the links, I've updated them accordingly

2020-11-07 22:51 UTC, nbcl reviewed
**Fixed:** Change citation hyperlinks to represent correct source.

2020-11-07 22:51 UTC, nbcl approved these changes
Approved! ✔️

2020-11-07 22:54 UTC, merged